version: '3'

services:
  mysql_db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_NAME=fidelity
      - MYSQL_USER=root
      - MYSQL_PASSWORD=lakshay6
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306


  web:
    build: . 
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - mysql_db
    environment:
      - DATABASE_HOST=mysql_db


volumes:
  db_data:
