# Generated by Django 5.1.6 on 2025-02-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('subject', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('qno', models.IntegerField()),
                ('ques', models.CharField(max_length=500)),
            ],
        ),
    ]
