# Generated by Django 5.1.6 on 2025-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('pId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('diam', models.IntegerField()),
                ('star', models.CharField(max_length=50)),
                ('rings', models.BooleanField(default=False)),
            ],
        ),
    ]
